from utils.models import (Question, FollowUpQuestion, Customer, Answer)
from utils.enums import YesNoQuestion, QuestionType, FollowUpConditionOperator

questions = {0: Question(question_id=0,
                         text='At what age do you plan to retire?',
                         question_type=QuestionType.NUMBER.value,
                         position=0,
                         is_follow_up=False),
             1: Question(question_id=1,
                         text='Do you currently have any life insurance coverage?',
                         question_type=QuestionType.YES_NO.value,
                         position=1,
                         follow_up_questions=[FollowUpQuestion(follow_up_question_id=2,
                                                               condition_operator=FollowUpConditionOperator.EQUALS.value,
                                                               condition_second_operand=YesNoQuestion.YES.value),
                                              FollowUpQuestion(follow_up_question_id=3,
                                                               condition_operator=FollowUpConditionOperator.EQUALS.value,
                                                               condition_second_operand=YesNoQuestion.YES.value),
                                              FollowUpQuestion(follow_up_question_id=4,
                                                               condition_operator=FollowUpConditionOperator.EQUALS.value,
                                                               condition_second_operand=YesNoQuestion.NO.value)
                                              ],
                         is_follow_up=False),
             2: Question(question_id=2,
                         text='What is the type of life insurance?',
                         question_type=QuestionType.DROPDOWN.value,
                         options=['Term', 'Whole Life', 'UL', 'IUL', 'VUL', 'Other'],
                         position=0,
                         is_follow_up=True),
             3: Question(question_id=3,
                         text='What is the amount?',
                         question_type=QuestionType.NUMBER.value,
                         position=1,
                         is_follow_up=True),
             4: Question(question_id=4,
                         text='What is the amount you are looking for?',
                         question_type=QuestionType.NUMBER.value,
                         position=2,
                         is_follow_up=True),
             5: Question(question_id=5,
                         text='Do you have any dependents?',
                         question_type=QuestionType.YES_NO.value,
                         follow_up_questions=[FollowUpQuestion(follow_up_question_id=6,
                                                               condition_operator=FollowUpConditionOperator.EQUALS.value,
                                                               condition_second_operand=YesNoQuestion.YES.value)],
                         position=2,
                         is_follow_up=False),
             6: Question(question_id=6,
                         text='Does any of your dependents have a chronic disease?',
                         question_type=QuestionType.YES_NO.value,
                         follow_up_questions=[FollowUpQuestion(follow_up_question_id=6,
                                                               condition_operator=FollowUpConditionOperator.EQUALS.value,
                                                               condition_second_operand=YesNoQuestion.YES.value)],
                         position=0,
                         is_follow_up=True),
             7: Question(question_id=7,
                         text='Which chronic disease does your dependent have?',
                         question_type=QuestionType.DROPDOWN.value,
                         position=0,
                         options=['Diabetes', 'Heart Disease', 'Cancer', 'Other'],
                         is_follow_up=True),
             8: Question(question_id=8,
                         text='What is your favorite joke?',
                         question_type=QuestionType.TEXT.value,
                         position=3,
                         is_follow_up=False),
             9: Question(question_id=9,
                         text='What is your profession?',
                         question_type=QuestionType.TEXT.value,
                         is_follow_up=False),
             }

customers = {0: Customer(customer_id=0,
                         first_name='Leonidas',
                         last_name='I',
                         email='king@sparta.gr',
                         phone='123456',
                         last_answers={0: Answer(question_id=0, value='50'),
                                       1: Answer(question_id=1, value=YesNoQuestion.YES.value),
                                       2: Answer(question_id=2, value='Term'),
                                       3: Answer(question_id=3, value='77777'),
                                       5: Answer(question_id=5, value=YesNoQuestion.NO.value),
                                       9: Answer(question_id=9, value="Au! Au! Au!"),
                                       }),
             1: Customer(customer_id=1,
                         first_name='Arty',
                         last_name='Abramovich',
                         email='a@gmail.com',
                         phone='123456'),
             2: Customer(customer_id=2,
                         first_name='test',
                         last_name='test',
                         email='test@gmail.com',
                         phone='123456')
             }


historical_answers = {}
