from base_models import (Question, FollowUpQuestion, QuestionOption, Option, Customer)
from db.db_models import Answer
from enums import YesNoQuestion, QuestionType, FollowUpConditionOperator

questions = [
    Question(question_id=0,
             text='At what age do you plan to retire?',
             question_type=QuestionType.NUMBER.value,
             position=0),
    Question(question_id=1,
             text='Do you currently have any life insurance coverage?',
             question_type=QuestionType.YES_NO.value,
             position=1),
    Question(question_id=2,
             text='What is the type of life insurance?',
             question_type=QuestionType.DROPDOWN.value,
             position=0),
    Question(question_id=3,
             text='What is the amount?',
             question_type=QuestionType.NUMBER.value,
             position=1),
    Question(question_id=4,
             text='What is the amount you are looking for?',
             question_type=QuestionType.NUMBER.value,
             position=2),
    Question(question_id=5,
             text='Do you have any dependents?',
             question_type=QuestionType.YES_NO.value,
             position=2),
    Question(question_id=6,
             text='Does any of your dependents have a chronic disease?',
             question_type=QuestionType.YES_NO.value,
             position=0),
    Question(question_id=7,
             text='Which chronic disease does your dependent have?',
             question_type=QuestionType.DROPDOWN.value,
             position=0),
    Question(question_id=8,
             text='What is your favorite joke?',
             question_type=QuestionType.TEXT.value,
             position=3),
    Question(question_id=9,
             text='What is your profession?',
             question_type=QuestionType.TEXT.value),
]

follow_up_questions = [
    FollowUpQuestion(main_question_id=1,
                     follow_up_question_id=2,
                     condition_operator=FollowUpConditionOperator.EQUALS.value,
                     condition_right_operand=YesNoQuestion.YES.value),
    FollowUpQuestion(main_question_id=1,
                     follow_up_question_id=3,
                     condition_operator=FollowUpConditionOperator.EQUALS.value,
                     condition_right_operand=YesNoQuestion.YES.value),
    FollowUpQuestion(main_question_id=1,
                     follow_up_question_id=4,
                     condition_operator=FollowUpConditionOperator.EQUALS.value,
                     condition_right_operand=YesNoQuestion.NO.value),
    FollowUpQuestion(main_question_id=5,
                     follow_up_question_id=6,
                     condition_operator=FollowUpConditionOperator.EQUALS.value,
                     condition_right_operand=YesNoQuestion.YES.value),
    FollowUpQuestion(main_question_id=5,
                     follow_up_question_id=7,
                     condition_operator=FollowUpConditionOperator.EQUALS.value,
                     condition_right_operand=YesNoQuestion.YES.value),
]

options = [
    Option(option_id=0, value='Term'),
    Option(option_id=1, value='Whole Life'),
    Option(option_id=2, value='UL'),
    Option(option_id=3, value='IUL'),
    Option(option_id=4, value='VUL'),
    Option(option_id=5, value='Other'),
    Option(option_id=6, value='Diabetes'),
    Option(option_id=7, value='Heart Disease'),
    Option(option_id=8, value='Cancer'),
]

question_options = [
    QuestionOption(option_id=0, question_id=2, position=0),
    QuestionOption(option_id=1, question_id=2, position=1),
    QuestionOption(option_id=2, question_id=2, position=2),
    QuestionOption(option_id=3, question_id=2, position=3),
    QuestionOption(option_id=4, question_id=2, position=4),
    QuestionOption(option_id=5, question_id=2, position=5),
    QuestionOption(option_id=6, question_id=7, position=0),
    QuestionOption(option_id=7, question_id=7, position=1),
    QuestionOption(option_id=8, question_id=7, position=2),
    QuestionOption(option_id=5, question_id=7, position=3),
]

customers = [
    Customer(customer_id=0,
             first_name='Leonidas',
             last_name='I',
             email='king@sparta.gr',
             phone='123456'),
    Customer(customer_id=1,
             first_name='Arty',
             last_name='Abramovich',
             email='a@gmail.com',
             phone='123456'),
    Customer(customer_id=2,
             first_name='test',
             last_name='test',
             email='test@gmail.com',
             phone='123456')
]

answers = [
    Answer(answer_id=0, customer_id=0, question_id=0, value='50'),
    Answer(answer_id=1, customer_id=0, question_id=0, value='60'),
    Answer(answer_id=2, customer_id=0, question_id=1, value=YesNoQuestion.YES.value),
    Answer(answer_id=2, customer_id=0, question_id=2, option_id=0),
    Answer(answer_id=3, customer_id=0, question_id=3, value='77777'),
    Answer(answer_id=4, customer_id=0, question_id=5, value=YesNoQuestion.NO.value),
    Answer(answer_id=5, customer_id=0, question_id=9, value="Au! Au! Au!"),
    Answer(answer_id=6, customer_id=1, question_id=0, value="37"),
    Answer(answer_id=7, customer_id=1, question_id=1, value=YesNoQuestion.NO.value),
    Answer(answer_id=8, customer_id=1, question_id=4, value='5555555'),
    Answer(answer_id=9, customer_id=1, question_id=5, value=YesNoQuestion.YES.value),
    Answer(answer_id=10, customer_id=1, question_id=6, value=YesNoQuestion.YES.value),
    Answer(answer_id=11, customer_id=1, question_id=7, option_id=5),
    Answer(answer_id=12, customer_id=1, question_id=9, value='programmer'),
]
